# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 11:33
from __future__ import unicode_literals

from django.db import migrations


def remove_djangocms_plugins(apps, schema_editor):
    LatestPostsPlugin = apps.get_model('djangocms_blog', 'LatestPostsPlugin')
    LatestPostsPlugin.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fds_blog', '0002_auto_20181214_1730'),
        ('djangocms_blog', '0035_posttranslation_subtitle'),
    ]

    operations = [
        migrations.RunPython(remove_djangocms_plugins)
    ]
