# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 11:33
from __future__ import unicode_literals

from django.db import migrations


def remove_djangocms_plugins(apps, schema_editor):
    try:
        LatestPostsPlugin = apps.get_model("djangocms_blog", "LatestPostsPlugin")
        LatestPostsPlugin.objects.all().delete()
    except Exception:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("fds_blog", "0002_auto_20181214_1730"),
    ]

    operations = [migrations.RunPython(remove_djangocms_plugins)]
