# Generated by Django 2.2.4 on 2019-10-01 14:44

import django.db.models.deletion
from django.db import migrations

import parler.fields


class Migration(migrations.Migration):
    dependencies = [
        ("fds_blog", "0004_auto_20181218_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="fds_blog.Category",
            ),
        ),
    ]
