# Generated by Django 3.2.12 on 2022-05-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("fds_blog", "0006_auto_20210505_1720"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePreviewPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="fds_blog_articlepreviewplugin",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fds_blog/plugins/latest_articles.html", "Normal"),
                            ("fds_blog/plugins/featured_articles.html", "Featured"),
                            ("fds_blog/plugins/simple_articles.html", "Simple"),
                            (
                                "fds_blog/plugins/slider_articles.html",
                                "Featured Slider",
                            ),
                        ],
                        help_text="template used to display the plugin",
                        max_length=250,
                        verbose_name="template",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_blog.article",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
