# Generated by Django 4.2.4 on 2024-04-19 14:59

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_blog", "0016_alter_article_start_publication"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="unique_blog_url",
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("slug"),
                models.F("language"),
                django.db.models.functions.datetime.Extract(
                    "start_publication", "year"
                ),
                django.db.models.functions.datetime.Extract(
                    "start_publication", "month"
                ),
                name="unique_blog_url",
                violation_error_message="An article with the same slug, month and year already exists. Please choose another slug.",
            ),
        ),
    ]
