# Generated by Django 4.2.4 on 2024-05-13 16:09

from django.db import migrations, models


def migrate_slider_template(apps, schema_editor):
    models = [
        apps.get_model("fds_blog", "articlepreviewplugin"),
        apps.get_model("fds_blog", "latestarticlesplugin"),
    ]

    for model in models:
        model.objects.filter(template="fds_blog/plugins/slider_articles.html").update(
            template="fds_blog/plugins/featured_articles.html"
        ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("fds_blog", "0017_remove_article_unique_blog_url_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_slider_template),
        migrations.AlterField(
            model_name="articlepreviewplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Normal"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/simple_articles.html", "Simple"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="latestarticlesplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Normal"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/simple_articles.html", "Simple"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
    ]
