# Generated by Django 4.2.4 on 2024-05-16 16:21

from django.db import migrations, models


def check_categories(apps, schema_editor):
    Article = apps.get_model("fds_blog", "Article")
    assert not Article.objects.filter(
        categories=None
    ).exists(), "You have uncategorized articles. Make sure every article has at least one category before applying this migration."


class Migration(migrations.Migration):
    dependencies = [
        ("fds_blog", "0019_remove_article_content_placeholder_category_color_and_more"),
    ]

    operations = [
        migrations.RunPython(check_categories),
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                related_name="articles",
                to="fds_blog.category",
                verbose_name="categories",
            ),
        ),
    ]
