# Generated by Django 4.2.4 on 2024-07-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_blog", "0020_alter_article_categories"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="categorytranslation",
            constraint=models.CheckConstraint(
                check=models.Q(("slug__regex", "^\\d+$"), _negated=True),
                name="not_just_digits_slug",
                violation_error_message="The slug may not only consist of digits.",
            ),
        ),
    ]
