# Generated by Django 4.2.4 on 2024-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_blog", "0021_categorytranslation_not_just_digits_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepreviewplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Normal"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/top_featured_articles.html", "Top Featured"),
                    ("fds_blog/plugins/simple_articles.html", "Simple"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="latestarticlesplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Normal"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/top_featured_articles.html", "Top Featured"),
                    ("fds_blog/plugins/simple_articles.html", "Simple"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
    ]
