# Generated by Django 4.2.16 on 2024-12-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_blog", "0024_alter_category_donation_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailsboxcmsplugin",
            name="inline",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_template",
            field=models.CharField(
                choices=[
                    ("fds_blog/_article_detail.html", "Default template"),
                    ("fds_blog/content/_article_no_image.html", "No image in article"),
                    ("fds_blog/content/_article_video_header.html", "Video header"),
                ],
                default="fds_blog/_article_detail.html",
                help_text="Template used to display the article's content.",
                max_length=250,
                verbose_name="content template",
            ),
        ),
    ]
