# Generated by Django 5.2.1 on 2025-05-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_blog', '0025_detailsboxcmsplugin_inline_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='fds_blog_ar_status_6edc57_idx',
            old_fields=('status', 'start_publication', 'end_publication'),
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='fds_blog_ar_slug_ded495_idx',
            old_fields=('slug', 'start_publication'),
        ),
    ]
