# Generated by Django 4.2.16 on 2025-05-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_blog", "0025_detailsboxcmsplugin_inline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepreviewplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Grid"),
                    ("fds_blog/plugins/simple_articles.html", "List"),
                    ("fds_blog/plugins/simple_articles_small.html", "List (compact)"),
                    ("fds_blog/plugins/simple_articles_text.html", "Text-only"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/top_featured_articles.html", "Top Featured"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="latestarticlesplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Grid"),
                    ("fds_blog/plugins/simple_articles.html", "List"),
                    ("fds_blog/plugins/simple_articles_small.html", "List (compact)"),
                    ("fds_blog/plugins/simple_articles_text.html", "Text-only"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/top_featured_articles.html", "Top Featured"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
    ]
