# Generated by Django 5.2.1 on 2025-06-26 12:32

from django.db import migrations, models

def migrate_article(apps, schema_editor):
    ArticlePreviewPlugin = apps.get_model("fds_blog", "ArticlePreviewPlugin")
    for plugin in ArticlePreviewPlugin.objects.filter(article__isnull=False):
        if plugin.article:
            plugin.articles.add(plugin.article)



class Migration(migrations.Migration):

    dependencies = [
        (
            "fds_blog",
            "0027_rename_article_status_start_publication_end_publication_fds_blog_ar_status_6edc57_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepreviewplugin",
            name="articles",
            field=models.ManyToManyField(to="fds_blog.article"),
        ),
        migrations.RunPython(migrate_article),
        migrations.RemoveField(
            model_name="articlepreviewplugin",
            name="article",
        ),
        migrations.AlterField(
            model_name="articlepreviewplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Grid"),
                    ("fds_blog/plugins/simple_articles.html", "List"),
                    ("fds_blog/plugins/simple_articles_small.html", "List (compact)"),
                    (
                        "fds_blog/plugins/simple_articles_small_row.html",
                        "List (compact, rows)",
                    ),
                    ("fds_blog/plugins/simple_articles_text.html", "Text-only"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/top_featured_articles.html", "Top Featured"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="latestarticlesplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fds_blog/plugins/latest_articles.html", "Grid"),
                    ("fds_blog/plugins/simple_articles.html", "List"),
                    ("fds_blog/plugins/simple_articles_small.html", "List (compact)"),
                    (
                        "fds_blog/plugins/simple_articles_small_row.html",
                        "List (compact, rows)",
                    ),
                    ("fds_blog/plugins/simple_articles_text.html", "Text-only"),
                    ("fds_blog/plugins/featured_articles.html", "Featured"),
                    ("fds_blog/plugins/top_featured_articles.html", "Top Featured"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
    ]
