# Generated by Django 5.2.10 on 2026-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_blog', '0028_remove_articlepreviewplugin_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detail_template',
            field=models.CharField(choices=[('fds_blog/article_detail.html', 'Default template'), ('fds_blog/article_detail_dark.html', 'Dark mode template')], default='fds_blog/article_detail.html', help_text="Template used to display the article's detail page.", max_length=250, verbose_name='detail template'),
        ),
        migrations.AlterField(
            model_name='article',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='You can link articles here that are part of a series.', to='fds_blog.article', verbose_name='related articles'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'None'), ('callout', 'Callout'), ('highlight', 'Highlight'), ('primary', 'Primary'), ('primary-subtle', 'Primary Subtle'), ('secondary', 'Secondary'), ('secondary-subtle', 'Secondary Subtle'), ('info', 'Info'), ('info-subtle', 'Info Subtle'), ('success', 'Success'), ('success-subtle', 'Success Subtle'), ('warning', 'Warning'), ('warning-subtle', 'Warning Subtle'), ('danger', 'Danger'), ('danger-subtle', 'Danger Subtle'), ('white', 'White'), ('light', 'Light'), ('light-subtle', 'Light Subtle'), ('dark', 'Dark'), ('dark-subtle', 'Dark Subtle'), ('body', 'Default Body'), ('body-secondary', 'Body Secondary'), ('body-tertiary', 'Body Tertiary'), ('gray-100', 'Gray 100'), ('gray-200', 'Gray 200'), ('gray-300', 'Gray 300'), ('gray-400', 'Gray 400'), ('gray-500', 'Gray 500'), ('gray-600', 'Gray 600'), ('gray-700', 'Gray 700'), ('gray-800', 'Gray 800'), ('gray-900', 'Gray 900'), ('blue-10', 'Blue 10'), ('blue-20', 'Blue 20'), ('blue-30', 'Blue 30'), ('blue-100', 'Blue 100'), ('blue-200', 'Blue 200'), ('blue-300', 'Blue 300'), ('blue-400', 'Blue 400'), ('blue-500', 'Blue 500'), ('blue-600', 'Blue 600'), ('blue-700', 'Blue 700'), ('blue-800', 'Blue 800'), ('yellow-100', 'Yellow 100'), ('yellow-200', 'Yellow 200'), ('yellow-300', 'Yellow 300'), ('purple', 'Purple'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('cyan', 'Cyan'), ('gray', 'Gray'), ('gray-dark', 'Gray Dark'), ('transparent', 'Transparent'), ('gray-100', 'Gray 100'), ('gray-200', 'Gray 200'), ('gray-300', 'Gray 300'), ('gray-400', 'Gray 400'), ('gray-500', 'Gray 500'), ('gray-600', 'Gray 600'), ('gray-700', 'Gray 700'), ('gray-800', 'Gray 800'), ('gray-900', 'Gray 900'), ('blue-10', 'Blue 10'), ('blue-20', 'Blue 20'), ('blue-30', 'Blue 30'), ('blue-100', 'Blue 100'), ('blue-200', 'Blue 200'), ('blue-300', 'Blue 300'), ('blue-400', 'Blue 400'), ('blue-500', 'Blue 500'), ('blue-600', 'Blue 600'), ('blue-700', 'Blue 700'), ('blue-800', 'Blue 800'), ('yellow-100', 'Yellow 100'), ('yellow-200', 'Yellow 200'), ('yellow-300', 'Yellow 300')], default='', help_text='Will be visible as the breadcrumb background.', max_length=50, verbose_name='Category color'),
        ),
    ]
