# Generated by Django 5.2.10 on 2026-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_blog', '0029_alter_article_detail_template_alter_article_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('de-ls', 'German (Easy Language)'), ('en', 'English')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='latestarticlesplugin',
            name='article_language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('de-ls', 'German (Easy Language)'), ('en', 'English')], default='de', max_length=5, verbose_name='language'),
        ),
    ]
