# Generated by Django 5.2.10 on 2026-04-23 12:16

import fragdenstaat_de.fds_blog.model_bases
import froide.helper.language
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_blog', '0029_alter_article_detail_template_alter_article_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_template',
            field=models.CharField(choices=fragdenstaat_de.fds_blog.model_bases.get_content_template_choices, default='fds_blog/_article_detail.html', help_text="Template used to display the article's content.", max_length=250, verbose_name='content template'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_template',
            field=models.CharField(choices=fragdenstaat_de.fds_blog.model_bases.get_detail_template_choices, default='fds_blog/article_detail.html', help_text="Template used to display the article's detail page.", max_length=250, verbose_name='detail template'),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=froide.helper.language.get_language_choices, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='latestarticlesplugin',
            name='article_language',
            field=models.CharField(blank=True, choices=froide.helper.language.get_language_choices, default=froide.helper.language.get_default_language, max_length=5, verbose_name='language'),
        ),
    ]
