# Generated by Django 5.2.10 on 2026-04-24 13:08

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_blog', '0030_alter_article_content_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='teaser',
            field=djangocms_text.fields.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='detailsboxcmsplugin',
            name='content',
            field=djangocms_text.fields.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='infotextboxcmsplugin',
            name='content',
            field=djangocms_text.fields.HTMLField(blank=True),
        ),
    ]
