# Generated by Django 5.2.10 on 2026-06-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_blog', '0031_alter_article_teaser_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='fds_blog_category_translation_uniq_lang'),
        ),
    ]
