# Generated by Django 4.2.16 on 2025-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_events", "0002_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
