# Generated by Django 5.2.6 on 2026-01-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("fds_events", "0004_eventtag_taggedevent_event_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="NextEventsCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "include_trials",
                    models.BooleanField(
                        default=False, help_text="Include trials from lawsuits."
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only show events with these tags",
                        to="fds_events.eventtag",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
