# Generated by Django 5.2.10 on 2026-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_events", "0005_nexteventscmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="nexteventscmsplugin",
            name="limit",
            field=models.IntegerField(default=0, help_text="0 means all events"),
        ),
        migrations.AlterField(
            model_name="nexteventscmsplugin",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only show events with these tags.",
                to="fds_events.eventtag",
            ),
        ),
    ]
