# Generated by Django 5.2.10 on 2026-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_events', '0006_nexteventscmsplugin_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'start_date', 'ordering': ('-start_date',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='short_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
    ]
