# Generated by Django 5.2.10 on 2026-05-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_events', '0007_alter_event_options_event_short_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, default='', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
