# Generated by Django 2.2.4 on 2019-10-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('fds_mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActionCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_mailing_emailactioncmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('action_label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
