# Generated by Django 2.2.4 on 2019-10-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0002_emailactioncmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='mail_intent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
