# Generated by Django 2.2.4 on 2019-11-04 14:56

from django.db import migrations, models
import django.db.models.deletion
import fragdenstaat_de.fds_mailing.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('fds_mailing', '0003_auto_20191029_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSectionCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_mailing_emailsectioncmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(fragdenstaat_de.fds_mailing.models.VariableTemplateMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='EmailStoryCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_mailing_emailstorycmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(fragdenstaat_de.fds_mailing.models.VariableTemplateMixin, 'cms.cmsplugin'),
        ),
    ]
