# Generated by Django 2.2.4 on 2019-11-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('fds_mailing', '0004_emailsectioncmsplugin_emailstorycmsplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(blank=True, choices=[('', 'Default template'), ('newsletter', 'Newsletter template')], max_length=255),
        ),
        migrations.CreateModel(
            name='EmailHeaderCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_mailing_emailheadercmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(max_length=255)),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
