# Generated by Django 2.2.4 on 2019-12-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0006_emailheadercmsplugin_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactioncmsplugin',
            name='action_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailstorycmsplugin',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
