# Generated by Django 2.2.4 on 2020-02-03 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0017_auto_20200131_1050'),
        ('fds_mailing', '0007_auto_20191216_1321'),
    ]
    run_before = [
        ('fds_newsletter', '0006_auto_20200203_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(default='info@fragdenstaat.de', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('publish', models.BooleanField(db_index=True, default=True, help_text='Publish in archive.', verbose_name='publish')),
                ('ready', models.BooleanField(default=False, verbose_name='ready')),
                ('submitted', models.BooleanField(default=False, editable=False, verbose_name='submitted')),
                ('sending_date', models.DateTimeField(blank=True, null=True, verbose_name='sending date')),
                ('sent_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='sent date')),
                ('sent', models.BooleanField(default=False, editable=False, verbose_name='sent')),
                ('sending', models.BooleanField(default=False, editable=False, verbose_name='sending')),
            ],
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ('-created',), 'verbose_name': 'email template', 'verbose_name_plural': 'email templates'},
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('bounced', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds_donation.Donor')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='fds_mailing.Mailing')),
            ],
        ),
    ]
