# Generated by Django 2.2.4 on 2020-02-03 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0005_auto_20200203_1728'),
        ('fds_mailing', '0008_auto_20200203_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds_newsletter.MailingSubscription'),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds_mailing.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.Newsletter'),
        ),
    ]
