# Generated by Django 3.0.5 on 2020-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0009_auto_20200203_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('-created',), 'verbose_name': 'mailing', 'verbose_name_plural': 'mailings'},
        ),
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'ordering': ('-sent',), 'verbose_name': 'mailing message', 'verbose_name_plural': 'mailing messages'},
        ),
        migrations.AlterField(
            model_name='emailactioncmsplugin',
            name='action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
