# Generated by Django 3.1.6 on 2021-02-12 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fds_mailing', '0010_auto_20200515_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='creator_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='sender_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
