# Generated by Django 3.1.8 on 2021-05-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0001_squashed_0010_auto_20210621_1022'),
        ('newsletter', '0005_auto_20190918_0122'),
        ('fds_mailing', '0011_auto_20210212_1326'),
    ]
    # run_before = [
    #     ('fds_newsletter', '0009_auto_20210526_2203')
    # ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='new_newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds_newsletter.newsletter'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.subscription'),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds_newsletter.subscriber'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(blank=True, choices=[('', 'Default template'), ('newsletter', 'Newsletter template'), ('formal', 'Formal email template')], max_length=255),
        ),
    ]
