# Generated by Django 3.1.8 on 2021-05-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0012_auto_20210526_2155'),
        ('fds_newsletter', '0001_squashed_0010_auto_20210621_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='newsletter',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='new_newsletter',
            new_name='newsletter',
        ),
        migrations.RemoveField(
            model_name='mailingmessage',
            name='subscription',
        ),
    ]
