# Generated by Django 4.2.16 on 2025-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0014_remove_emailtemplate_email_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(blank=True, choices=[('', 'Default template'), ('newsletter', 'Newsletter template'), ('formal', 'Formal email template'), ('mjml', 'MJML email template')], max_length=255),
        ),
    ]
