# Generated by Django 4.2.16 on 2025-04-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0006_segment_taggedsubscriber_created_taggedsegment_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fds_mailing', '0015_alter_emailtemplate_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessageReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='segments',
            field=models.ManyToManyField(blank=True, to='fds_newsletter.segment'),
        ),
        migrations.AddConstraint(
            model_name='mailingmessage',
            constraint=models.UniqueConstraint(fields=('mailing', 'email'), name='unique_mailing_email'),
        ),
        migrations.AddConstraint(
            model_name='mailingmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('subscriber__isnull', False)), fields=('mailing', 'subscriber'), name='unique_mailing_subscriber'),
        ),
        migrations.AddConstraint(
            model_name='mailingmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('mailing', 'user'), name='unique_mailing_user'),
        ),
        migrations.AddField(
            model_name='mailingmessagereference',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mailingmessagereference',
            name='mailing_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fds_mailing.mailingmessage'),
        ),
        migrations.AddIndex(
            model_name='mailingmessagereference',
            index=models.Index(fields=['content_type', 'object_id'], name='fds_mailing_content_f514ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailingmessagereference',
            constraint=models.UniqueConstraint(fields=('mailing_message', 'content_type'), name='unique_mailing_message_content_type'),
        ),
    ]
