# Generated by Django 4.2.16 on 2025-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0016_mailingmessagereference_mailing_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='preheader',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
