# Generated by Django 4.2.16 on 2025-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0017_emailtemplate_preheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='publish',
            field=models.BooleanField(db_index=True, default=False, help_text='Publish in archive.', verbose_name='publish'),
        ),
    ]
