# Generated by Django 4.2.16 on 2025-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0018_alter_mailing_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='tracking',
            field=models.BooleanField(default=False, help_text='Track opens and clicks.', verbose_name='tracking'),
        ),
    ]
