# Generated by Django 4.2.16 on 2025-04-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0019_mailing_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='open_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the email was opened.', verbose_name='open count'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='open_log_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
