# Generated by Django 4.2.16 on 2025-04-30 11:35

from django.db import migrations, models
import django.db.models.deletion
import djangocms_frontend.fields
import fragdenstaat_de.fds_mailing.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('fds_mailing', '0020_mailing_open_count_mailing_open_log_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailButtonCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('action_label', models.CharField(blank=True, max_length=255)),
                ('attributes', djangocms_frontend.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
            ],
            bases=(fragdenstaat_de.fds_mailing.models.VariableTemplateMixin, 'cms.cmsplugin'),
        ),
    ]
