# Generated by Django 4.2.16 on 2025-04-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('fds_mailing', '0021_emailbuttoncmsplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('context_key', models.CharField(help_text='Key to check in the context.', max_length=255)),
                ('context_value', models.CharField(blank=True, help_text='Optional value to check on key. Checks for presence if empty.', max_length=255)),
                ('negate', models.BooleanField(default=False, help_text='Negate the condition.')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
