# Generated by Django 5.2.4 on 2025-07-14 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0063_alter_recurrence_options_recurrence_active'),
        ('fds_mailing', '0022_conditioncmsplugin'),
        ('fds_newsletter', '0009_segment_negate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousMailing',
            fields=[
            ],
            options={
                'verbose_name': 'continuous mailing',
                'verbose_name_plural': 'continuous mailings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fds_mailing.mailing',),
        ),
        migrations.RemoveConstraint(
            model_name='mailingmessage',
            name='unique_mailing_email',
        ),
        migrations.RemoveConstraint(
            model_name='mailingmessage',
            name='unique_mailing_user',
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_continuous',
            field=models.BooleanField(default=False, help_text='This mailing is a continuous mailing that tracks transactional messages.', verbose_name='is continuous'),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='is_continuous',
            field=models.BooleanField(default=False, help_text='This message is part of a continuous mailing that tracks transactional messages.', verbose_name='is continuous'),
        ),
        migrations.AddConstraint(
            model_name='mailingmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_continuous', False)), fields=('mailing', 'email'), name='unique_mailing_email'),
        ),
        migrations.AddConstraint(
            model_name='mailingmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_continuous', False), ('user__isnull', False)), fields=('mailing', 'user'), name='unique_mailing_user'),
        ),
    ]
