# Generated by Django 5.2.4 on 2025-07-21 10:28

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0023_continuousmailing_and_more'),
        ('fds_newsletter', '0010_taggedsubscriber_unique_tagged_subscriber'),
        ('flowcontrol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayMailActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Number of days to wait between emails.')),
                ('max_delay_days', models.PositiveIntegerField(default=0, help_text='Maximum number of days to wait between emails. 0 means no limit.')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
        migrations.CreateModel(
            name='SendMailActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
        migrations.AlterModelManagers(
            name='mailing',
            managers=[
                ('all_mailings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='mailing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_continuous', True), ('ready', True)), fields=('email_template',), name='unique_continuous_mailing_emailtemplate'),
        ),
        migrations.AddField(
            model_name='sendmailactionconfig',
            name='email_template',
            field=models.ForeignKey(help_text='Email template to use for this action.', on_delete=django.db.models.deletion.CASCADE, to='fds_mailing.emailtemplate'),
        ),
    ]
