# Generated by Django 5.2.10 on 2026-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0024_delaymailactionconfig_sendmailactionconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterarchivecmsplugin',
            name='number_of_mailings',
            field=models.PositiveIntegerField(default=6, help_text='0 means all the mailings. Should be divisible by 3.', verbose_name='number of mailing'),
        ),
    ]
