# Generated by Django 5.2.10 on 2026-04-23 12:16

import fragdenstaat_de.fds_mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0025_alter_newsletterarchivecmsplugin_number_of_mailings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='sender_email',
            field=models.EmailField(default=fragdenstaat_de.fds_mailing.models.get_default_sender_email, max_length=255),
        ),
    ]
