# Generated by Django 5.2.10 on 2026-04-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('fds_mailing', '0026_alter_mailing_sender_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCodeCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('code', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
