# Generated by Django 5.2.15 on 2026-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0027_rawcodecmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmailactionconfig',
            name='only_once',
            field=models.BooleanField(default=True, help_text='Only send this email once to this contact.'),
        ),
    ]
