# Generated by Django 5.2.15 on 2026-07-30 15:09

import django.db.models.deletion
import fragdenstaat_de.fds_mailing.models
import fragdenstaat_de.fds_mailing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0028_sendmailactionconfig_only_once'),
        ('flowcontrol', '0007_alter_flowrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='sender_email',
            field=models.EmailField(default=fragdenstaat_de.fds_mailing.models.get_default_sender_email, max_length=255, validators=[fragdenstaat_de.fds_mailing.validators.validate_sender_domain]),
        ),
        migrations.CreateModel(
            name='HasReceivedMailingActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('negate', models.BooleanField(default=False, help_text='Negate the condition.')),
                ('mailing', models.ForeignKey(help_text='Mailing to check.', on_delete=django.db.models.deletion.CASCADE, to='fds_mailing.mailing')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
    ]
