# Generated by Django 5.2.15 on 2026-09-25 13:22

import flowcontrol.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0029_alter_mailing_sender_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioncmsplugin',
            name='condition',
            field=models.TextField(default='False', validators=[flowcontrol.utils.validate_template_condition]),
            preserve_default=False,
        ),
    ]
