# Generated by Django 5.2.15 on 2026-09-25 13:24

from django.db import migrations


def migrate_condition(apps, schema_editor):
    ConditionCMSPlugin = apps.get_model("fds_mailing", "ConditionCMSPlugin")

    for instance in ConditionCMSPlugin.objects.all():
        instance.condition = "%s%s%s%s" % (
            "not " if instance.negate else "",
            instance.context_key,
            " == " if instance.context_value else "",
            instance.context_value,
        )
        instance.save(update_fields=["condition"])


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0030_conditioncmsplugin_condition'),
    ]

    operations = [
        migrations.RunPython(migrate_condition)
    ]
