# Generated by Django 5.2.15 on 2026-09-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0031_auto_20260925_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditioncmsplugin',
            name='context_key',
        ),
        migrations.RemoveField(
            model_name='conditioncmsplugin',
            name='context_value',
        ),
        migrations.RemoveField(
            model_name='conditioncmsplugin',
            name='negate',
        ),
    ]
