import '../styles/gegenrechtsschutz.scss'

import 'froide/frontend/javascript/snippets/bootstrap'
import 'froide/frontend/javascript/snippets/copy-text'
import 'froide/frontend/javascript/snippets/form-ajax'
import 'froide/frontend/javascript/snippets/misc'
import 'froide/frontend/javascript/snippets/share-links'
import 'froide/frontend/javascript/snippets/inline-edit-forms'
import 'froide/frontend/javascript/snippets/color-mode'

import './magnifier'
import './misc'
import './navbar'
import './slider.js'
import './smooth-scroll'
import './banner'
import './donation-form'
