import "./misc/onion-darkmode"
import "./misc/iframe-height"
import "./misc/matomo"
import "./misc/reference-forms"
import "./misc/secpol-violation"
import "./misc/shuffle-items"
import "./misc/userfill-forms"
import "./misc/video-modals"