# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 10:07
from __future__ import unicode_literals

from django.db import migrations


def subscribe_newsletter(apps, schema_editor):
    Newsletter = apps.get_model('newsletter', 'Newsletter')
    newsletter, created = Newsletter.objects.get_or_create(
        slug='fragdenstaat',
        defaults={
            'title': 'FragDenStaat-Newsletter',
            'email': 'info@fragdenstaat.de',
            'sender': 'FragDenStaat.de',
            'visible': True,
            'send_html': False
        }
    )
    Subscription = apps.get_model('newsletter', 'Subscription')
    User = apps.get_model('account', 'User')

    for user in User.objects.filter(active=True, newsletter=True):
        Subscription.objects.create(
            user=user,
            newsletter=newsletter,
            subscribed=True,
            subscribe_date=user.date_joined
        )


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_date_deactivated'),
        ('newsletter', '0004_auto_20180407_1043'),
    ]

    operations = [
        migrations.RunPython(subscribe_newsletter),
    ]
