# Generated by Django 2.2.4 on 2019-10-30 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0003_auto_20191029_1734'),
        ('fds_newsletter', '0002_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('publish', models.BooleanField(db_index=True, default=True, help_text='Im Archiv einsehbar.', verbose_name='veröffentlichen')),
                ('ready', models.BooleanField(default=False, verbose_name='bereit')),
                ('submitted', models.BooleanField(default=False, editable=False, verbose_name='submitted')),
                ('sending_date', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('sent', models.BooleanField(default=False, editable=False, verbose_name='gesendet')),
                ('sending', models.BooleanField(default=False, editable=False, verbose_name='wird gesendet')),
                ('email_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds_mailing.EmailTemplate')),
                ('newsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.Newsletter')),
                ('subscriptions', models.ManyToManyField(help_text='Falls Sie keine auswählen, wird das System automatisch Abonnenten auswählen.', limit_choices_to={'subscribed': True}, to='newsletter.Subscription', verbose_name='Empfänger')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
            },
        ),
    ]
