# Generated by Django 3.2.4 on 2021-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_newsletter", "0002_auto_20210707_2036"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
