# Generated by Django 2.2.4 on 2019-10-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0003_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='sending_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='sending date'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sent_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='sent date'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, help_text='Falls Sie keine auswählen, wird das System automatisch Abonnenten auswählen.', limit_choices_to={'subscribed': True}, to='newsletter.Subscription', verbose_name='Empfänger'),
        ),
    ]
