# Generated by Django 4.2.4 on 2024-05-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_newsletter", "0004_alter_newslettercmsplugin_cmsplugin_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnsubscribeFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("too_much", "I received too many emails"),
                            (
                                "expected_updates",
                                "I expected more updates regarding certain campaings",
                            ),
                            (
                                "specific_request",
                                "I only signed up regarding a specific FOI request",
                            ),
                            ("not_interested", "The topics are not interesting to me"),
                            ("dislike", "I don't like your work anymore"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.newsletter",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Unsubscribe Feedback",
            },
        ),
        migrations.AddConstraint(
            model_name="unsubscribefeedback",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "newsletter"), name="unique_feedback_subscriber"
            ),
        ),
    ]
