# Generated by Django 2.2.4 on 2020-02-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0005_auto_20200203_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fds_mailing.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='newsletter.Newsletter'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sending_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sending date'),
        ),
    ]
