# Generated by Django 4.2.16 on 2025-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0006_segment_taggedsubscriber_created_taggedsegment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
