# Generated by Django 2.2.4 on 2020-02-03 16:44

from django.db import migrations
from django.conf import settings


def port_to_fds_mailing(apps, schema_editor):
    Mailing = apps.get_model('fds_mailing', 'Mailing')
    MailingMessage = apps.get_model('fds_mailing', 'MailingMessage')
    OldMailing = apps.get_model('fds_newsletter', 'Mailing')

    for old_mailing in OldMailing.objects.all():
        mailing = Mailing.objects.create(
            name=old_mailing.email_template.name,
            email_template=old_mailing.email_template,
            newsletter=old_mailing.newsletter,
            sender_name=old_mailing.sender_name,
            sender_email=settings.SITE_EMAIL,
            created=old_mailing.created,
            publish=old_mailing.publish,
            ready=old_mailing.ready,
            submitted=old_mailing.submitted,
            sending_date=old_mailing.sending_date,
            sent_date=old_mailing.sent_date,
            sent=old_mailing.sent,
            sending=old_mailing.sending,
        )
        for sub in old_mailing.subscriptions.all():
            name = sub.name_field or ''
            email = sub.email_field or ''
            if sub.user:
                name = '{} {}'.format(
                    sub.user.first_name,
                    sub.user.last_name
                ).strip()
                email = sub.user.email
            MailingMessage.objects.create(
                mailing=mailing,
                name=name,
                email=email,
                sent=old_mailing.sent_date,
                subscription=sub,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0006_auto_20200203_1732'),
    ]

    operations = [
        migrations.RunPython(port_to_fds_mailing),
    ]
