# Generated by Django 4.2.16 on 2025-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0007_subscriber_unsubscribe_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subscribed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='unsubscribefeedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='unsubscribefeedback',
            name='reason',
            field=models.CharField(choices=[('too_much', 'I received too many emails'), ('expected_updates', 'I expected more updates regarding certain campaings'), ('specific_request', 'I only signed up regarding a specific FOI request'), ('not_interested', 'The topics are not interesting to me'), ('dislike', "I don't like your work anymore"), ('other', 'Other')], max_length=50, verbose_name='Reason'),
        ),
    ]
