# Generated by Django 5.2.4 on 2025-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0008_newsletter_subscribed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='negate',
            field=models.BooleanField(default=False, verbose_name='negate tags'),
        ),
    ]
