# Generated by Django 3.1.8 on 2021-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0009_auto_20210526_2203'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriber',
            name='newsletter_subscription_user_email'
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email__isnull', False), ('user__isnull', True)), models.Q(('email__isnull', True), ('user__isnull', False)), models.Q(('email__isnull', True), ('unsubscribed__isnull', False), ('user__isnull', True)), _connector='OR'), name='newsletter_subscription_user_email'),
        )
    ]
