# Generated by Django 5.2.4 on 2025-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0009_segment_negate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taggedsubscriber',
            constraint=models.UniqueConstraint(fields=('tag', 'content_object'), name='unique_tagged_subscriber'),
        ),
    ]
