# Generated by Django 5.2.10 on 2026-02-08 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0024_delaymailactionconfig_sendmailactionconfig_and_more'),
        ('fds_newsletter', '0010_taggedsubscriber_unique_tagged_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='already_subscribed_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fds_mailing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='confirm_batch_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fds_mailing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='confirm_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fds_mailing.emailtemplate'),
        ),
    ]
