# Generated by Django 5.2.10 on 2026-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0011_newsletter_already_subscribed_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
