# Generated by Django 5.2.10 on 2026-02-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0012_subscriber_data'),
        ('flowcontrol', '0002_trigger_condition_alter_flowrun_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeToNewsletterActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fds_newsletter.newsletter')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
    ]
