# Generated by Django 5.2.10 on 2026-03-19 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_mailing', '0025_alter_newsletterarchivecmsplugin_number_of_mailings'),
        ('fds_newsletter', '0013_subscribetonewsletteractionconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_file', models.FileField(help_text="CSV file with 'email' and optional 'name' or 'first_name', 'last_name' and 'tags' columns.", upload_to='newsletter_import')),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('new_tags', models.CharField(blank=True, max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('imported_count', models.IntegerField(blank=True, null=True)),
                ('activation_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds_mailing.emailtemplate')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fds_newsletter.newsletter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscriber Import',
                'verbose_name_plural': 'Subscriber Imports',
                'ordering': ('-created',),
            },
        ),
    ]
