# Generated by Django 5.2.10 on 2026-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0014_subscriberimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberimport',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
