# Generated by Django 5.2.10 on 2026-05-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0015_subscriberimport_started'),
        ('flowcontrol', '0005_emailalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberTagActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('remove', models.BooleanField(default=False, help_text='If checked will remove the tag from the subscriber instead of adding it.', verbose_name='Remove tag')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fds_newsletter.subscribertag', verbose_name='Subscriber Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
    ]
