# Generated by Django 5.2.15 on 2026-07-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0016_subscribertagactionconfig'),
        ('flowcontrol', '0006_trigger_reset_to_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasTagActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('negate', models.BooleanField(default=False, help_text="If doesn't have tag", verbose_name='Negate condition')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fds_newsletter.subscribertag', verbose_name='Subscriber Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
        migrations.CreateModel(
            name='InSegmentActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('negate', models.BooleanField(default=False, help_text='If not in segment', verbose_name='Negate condition')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fds_newsletter.segment', verbose_name='Segment')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
    ]
