# Generated by Django 5.2.15 on 2026-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0017_hastagactionconfig_insegmentactionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberimport',
            name='data_columns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriberimport',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
