# Generated by Django 5.2.15 on 2026-07-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0018_subscriberimport_data_columns_subscriberimport_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='default_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fds_newsletter.segment'),
        ),
    ]
