# Generated by Django 5.2.15 on 2026-07-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_newsletter', '0019_newsletter_default_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedSegment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fds_newsletter.segment',),
        ),
        migrations.AddField(
            model_name='segment',
            name='archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
