# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0002_documentpagescmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpagescmsplugin",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
