# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 12:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0006_documentembedcmsplugin"),
        ("document", "0008_auto_20180807_1452"),
    ]
    run_before = [
        ("document", "0011_auto_20180810_1455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageannotationcmsplugin",
            name="page_annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="filingcabinet.PageAnnotation",
            ),
        ),
    ]
