# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fds_cms', '0007_auto_20180810_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foirequestlistcmsplugin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
