# Generated by Django 2.1.7 on 2019-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0011_oneclickfoirequestcmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="oneclickfoirequestcmsplugin",
            name="redirect_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
