# Generated by Django 2.2.4 on 2019-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0013_oneclickfoirequestcmsplugin_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpagescmsplugin",
            name="size",
            field=models.CharField(
                choices=[("small", "Small"), ("normal", "Normal"), ("large", "Large")],
                default="small",
                max_length=10,
            ),
        ),
    ]
