# Generated by Django 2.2.4 on 2019-10-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('fds_cms', '0014_documentpagescmsplugin_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegaChartCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_cms_vegachartcmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vega_json', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
