# Generated by Django 3.0.5 on 2020-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_cms', '0027_auto_20200610_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarylinkcmsplugin',
            name='link_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
