# Generated by Django 3.1.8 on 2021-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_cms", "0029_auto_20200612_1243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foirequestlistcmsplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default template"),
                    ("foirequest/cms_plugins/list_follow.html", "Follow template"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
    ]
