# Generated by Django 3.1.8 on 2021-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_cms', '0031_documentportalembedcmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidercmsplugin',
            name='wrapper_classes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
