# Generated by Django 3.2.8 on 2021-12-06 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('fds_cms', '0034_cardcmsplugin_cardheadercmsplugin_cardinnercmsplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcmsplugin',
            name='spacing',
            field=models.CharField(choices=[('sm', 'Small'), ('lg', 'Large')], default='sm', max_length=3, verbose_name='Spacing'),
        ),
        migrations.AlterField(
            model_name='cardheadercmsplugin',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CardImageCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_cms_cardimagecmsplugin', serialize=False, to='cms.cmsplugin')),
                ('overlap', models.CharField(choices=[('top', 'Top'), ('left', 'Left'), ('right', 'Right')], default='top', max_length=10, verbose_name='Overlap')),
                ('extra_classes', models.CharField(blank=True, max_length=255)),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
