# Generated by Django 3.2.11 on 2022-01-17 14:05

from django.db import migrations

import djangocms_bootstrap4.fields

models = (
    "cardcmsplugin",
    "cardheadercmsplugin",
    "cardiconcmsplugin",
    "cardimagecmsplugin",
)


def migrate_extraclasses(apps, schema_editor):
    for model in models:
        Model = apps.get_model("fds_cms", model)

        items = Model.objects.filter(extra_classes__isnull=False)
        for item in items:
            item.attributes["class"] = item.extra_classes
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0035_alter_cardimagecmsplugin_overlap"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardheadercmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardiconcmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardimagecmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardinnercmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.RunPython(migrate_extraclasses, atomic=False),
    ]
