# Generated by Django 3.2.8 on 2021-12-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('fds_cms', '0035_auto_20211206_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIconCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_cms_cardiconcmsplugin', serialize=False, to='cms.cmsplugin')),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('extra_classes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='cardcmsplugin',
            name='border',
            field=models.CharField(choices=[('none', 'None'), ('blue', 'Blue'), ('gray', 'Gray'), ('yellow', 'Yellow')], default='gray', max_length=50, verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='cardimagecmsplugin',
            name='overlap',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10, verbose_name='Overlap'),
        ),
    ]
