# Generated by Django 3.2.8 on 2021-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_cms', '0036_auto_20211209_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiconcmsplugin',
            name='overlap',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10, verbose_name='Overlap'),
        ),
        migrations.AlterField(
            model_name='cardcmsplugin',
            name='spacing',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='lg', max_length=3, verbose_name='Spacing'),
        ),
    ]
