# Generated by Django 3.2.11 on 2022-01-20 15:11

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_bootstrap4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('fds_cms', '0037_remove_extraclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLinkCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fds_cms_cardlinkcmsplugin', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('arrow', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('attributes', djangocms_bootstrap4.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('page_link', cms.models.fields.PageField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('icon', models.CharField(blank=True, help_text='Enter an icon name from the <a href="https://fontawesome.com/v4.7.0/icons/" target="_blank">FontAwesome 4 icon set</a>', max_length=50, verbose_name='Icon')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
