# Generated by Django 3.2.11 on 2022-01-24 11:28

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('fds_cms', '0038_cardlinkcmsplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlinkcmsplugin',
            name='page_link',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
    ]
