# Generated by Django 3.2.11 on 2022-02-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0039_alter_cardlinkcmsplugin_page_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcmsplugin",
            name="background",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("info", "Info"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("danger", "Danger"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("yellow", "Yellow"),
                    ("cyan", "Cyan"),
                    ("gray", "Gray"),
                    ("gray-dark", "Gray Dark"),
                    ("white", "White"),
                    ("gray-100", "Gray 100"),
                    ("gray-200", "Gray 200"),
                    ("gray-300", "Gray 300"),
                    ("gray-400", "Gray 400"),
                    ("gray-500", "Gray 500"),
                    ("gray-600", "Gray 600"),
                    ("gray-700", "Gray 700"),
                    ("gray-800", "Gray 800"),
                    ("gray-900", "Gray 900"),
                    ("blue-10", "Blue 10"),
                    ("blue-20", "Blue 20"),
                    ("blue-30", "Blue 30"),
                    ("blue-100", "Blue 100"),
                    ("blue-200", "Blue 200"),
                    ("blue-300", "Blue 300"),
                    ("blue-400", "Blue 400"),
                    ("blue-500", "Blue 500"),
                    ("blue-600", "Blue 600"),
                    ("blue-700", "Blue 700"),
                    ("blue-800", "Blue 800"),
                    ("yellow-100", "Yellow 100"),
                    ("yellow-200", "Yellow 200"),
                    ("yellow-300", "Yellow 300"),
                ],
                default="",
                max_length=50,
                verbose_name="Background",
            ),
        ),
    ]
