# Generated by Django 3.2.11 on 2022-02-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_cms', '0041_migrate_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinnercmsplugin',
            name='background',
        ),
    ]
