# Generated by Django 3.2.11 on 2022-02-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0042_remove_cardinnercmsplugin_background"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designcontainercmsplugin",
            name="style",
        ),
    ]
