# Generated by Django 3.2.11 on 2022-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_cms", "0043_remove_designcontainercmsplugin_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardimagecmsplugin",
            name="size",
            field=models.CharField(
                choices=[
                    ("sm", "Small"),
                    ("lg", "Large"),
                ],
                default="lg",
                max_length=10,
                verbose_name="Size",
            ),
        ),
    ]
