# Generated by Django 3.2.14 on 2022-08-26 12:18

import re

from django.db import migrations
from django.conf import settings

REGEX_LIST = (
    (r"^([mp])l(-[mdslgx]+)?(-[0-5])$", r"\1s\2\3"),
    (r"^([mp])r(-[mdslgx]+)?(-[0-5])$", r"\1e\2\3"),
    (r"^([mp])l(-[mdslgx]+)?-auto$", r"\1s\2-auto"),
    (r"^([mp])r(-[mdslgx]+)?-auto$", r"\1e\2-auto"),
    (r"^no-gutters$", r"g-0"),
    (r"^input-group-append$", r""),
    (r"^input-group-prepend$", r""),
    (r"^form-group$", r"mb-3"),
    (r"^form-row$", r"row"),
    (r"^pull-right$", r"float-end"),
    (r"^pull-left$", r"float-start"),
    (r"^left(-[0-9]*)$", r"start\1"),
    (r"^right(-[0-9]*)$", r"end\1"),
    (r"^text-monospace$", r"font-monospace"),
    (r"^(float|rounded|text)-left$", r"\1-start"),
    (r"^(float|rounded|text)-right$", r"\1-end"),
    (r"^font-weight(-[a-zA-Z]*)$", r"fw\1"),
    (r"^font-style(-[a-zA-Z]*)$", r"fst\1"),
    (r"^badge-pill$", r"rounded-pill"),
    (r"^badge(-[a-zA-Z]*)$", r"text-bg\1"),
    (r"^sr-only-focusable$", r"visually-hidden-focusable"),
    (r"^sr-only$", r"visually-hidden"),
)


def convert_classes(class_str):
    if not class_str:
        return
    parts = class_str.split()
    result = []
    for part in parts:
        for pattern, repl in REGEX_LIST:
            part = re.sub(pattern, repl, part)
        result.append(part)
    result_str = " ".join(result)
    if result_str != class_str:
        print("Convert {} to {}".format(class_str, result_str))
    return result_str


def update_attributes(obj):
    class_str = obj.attributes.get("class")
    if not class_str:
        return
    class_str = convert_classes(class_str)
    obj.save(update_fields=["attributes"])


def update_extra_classes(obj):
    if not obj.extra_classes:
        return
    obj.extra_classes = convert_classes(obj.extra_classes)
    obj.save(update_fields=["extra_classes"])


PLUGIN_MODELS = (
    ("fds_cms", "PrimaryLinkCMSPlugin", update_extra_classes),
    ("fds_cms", "DesignContainerCMSPlugin", update_extra_classes),
    ("fds_cms", "CollapsibleCMSPlugin", update_extra_classes),
    ("fds_cms", "SliderCMSPlugin", update_extra_classes),
    ("fds_donation", "DonationFormCMSPlugin", update_extra_classes),
    ("froide_govplan", "GovernmentPlansCMSPlugin", update_extra_classes),
    ("fds_cms", "ModalCMSPlugin", update_attributes),
    ("fds_cms", "CardCMSPlugin", update_attributes),
    ("fds_cms", "CardInnerCMSPlugin", update_attributes),
    ("fds_cms", "CardHeaderCMSPlugin", update_attributes),
    ("fds_cms", "CardImageCMSPlugin", update_attributes),
    ("fds_cms", "CardIconCMSPlugin", update_attributes),
    ("fds_cms", "CardLinkCMSPlugin", update_attributes),
    ("fds_cms", "RevealMoreCMSPlugin", update_attributes),
    ("fds_cms", "BorderedSectionCMSPlugin", update_attributes),
)


def convert_bootstrap_classes(apps, schema_editor):
    for app_name, model_name, mod_func in PLUGIN_MODELS:
        plugin_model = apps.get_model(app_name, model_name)
        for obj in plugin_model.objects.all():
            mod_func(obj)


class Migration(migrations.Migration):
    dependencies = [
        ("fds_cms", "0051_auto_20220826_1234"),
    ]

    if "fragdenstaat_de.fds_donation.apps.FdsDonationConfig" in settings.INSTALLED_APPS:
        dependencies += [   
            ("fds_donation", "0037_donationprogressbarcmsplugin_white_text"),
            ("froide_govplan", "0011_governmentplan_properties"),
        ]

    operations = [
        migrations.RunPython(convert_bootstrap_classes),
    ]
