# Generated by Django 3.2.14 on 2022-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fds_cms", "0052_auto_20220826_1418"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardiconcmsplugin",
            name="overlap",
        ),
    ]
