# Generated by Django 4.0.7 on 2022-11-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("fds_cms", "0053_remove_cardiconcmsplugin_overlap"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropdownBannerCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "animation",
                    models.BooleanField(
                        verbose_name="Slide banner with animation", default=True
                    ),
                ),
                (
                    "dark",
                    models.BooleanField(
                        verbose_name="Banner is dark-themed, button should therefore be light",
                        default=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        )
    ]
