# Generated by Django 4.1.4 on 2023-02-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("fds_cms", "0056_designcontainercmsplugin_backdrop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designcontainercmsplugin",
            name="backdrop",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("50", "50 %"), ("75", "75 %")],
                default="",
                max_length=5,
                verbose_name="Backdrop",
            ),
        )
    ]
