# Generated by Django 4.2.4 on 2023-12-11 14:56

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fds_cms", "0058_remove_designcontainercmsplugin_template_and_more"),
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="fdspageextension",
            name="breadcrumb_ancestor",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="If present, this page will be displayed as the ancestor in the breadcrumbs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breadcrumb_ancestor",
                to="cms.page",
                verbose_name="Ancestor",
            ),
        ),
        migrations.AddField(
            model_name="fdspageextension",
            name="ancestor_only_upwards",
            field=models.BooleanField(
                default=True,
                verbose_name="Only show the breadcrumb ancestor on this page, but not its children",
            ),
        ),
        migrations.AddField(
            model_name="fdspageextension",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text='Enter an icon name from the <a href="https://fontawesome.com/v4.7.0/icons/" target="_blank">FontAwesome 4 icon set</a>',
                max_length=50,
                verbose_name="Icon",
            ),
        ),
        migrations.AddField(
            model_name="fdspageextension",
            name="breadcrumb_background",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("callout", "Callout"),
                    ("highlight", "Highlight"),
                    ("body", "Default Body"),
                    ("body-secondary", "Body Secondary"),
                    ("body-tertiary", "Body Tertiary"),
                    ("dark-subtle", "Dark Subtle"),
                    ("light-subtle", "Light Subtle"),
                    ("primary", "Primary"),
                    ("primary-subtle", "Primary Subtle"),
                    ("secondary", "Secondary"),
                    ("secondary-subtle", "Secondary Subtle"),
                    ("info", "Info"),
                    ("info-subtle", "Info Subtle"),
                    ("success", "Success"),
                    ("success-subtle", "Success Subtle"),
                    ("warning", "Warning"),
                    ("warning-subtle", "Warning Subtle"),
                    ("danger", "Danger"),
                    ("danger-subtle", "Danger Subtle"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("yellow", "Yellow"),
                    ("cyan", "Cyan"),
                    ("gray", "Gray"),
                    ("gray-dark", "Gray Dark"),
                    ("white", "White"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("transparent", "Transparent"),
                    ("gray-100", "Gray 100"),
                    ("gray-200", "Gray 200"),
                    ("gray-300", "Gray 300"),
                    ("gray-400", "Gray 400"),
                    ("gray-500", "Gray 500"),
                    ("gray-600", "Gray 600"),
                    ("gray-700", "Gray 700"),
                    ("gray-800", "Gray 800"),
                    ("gray-900", "Gray 900"),
                    ("blue-10", "Blue 10"),
                    ("blue-20", "Blue 20"),
                    ("blue-30", "Blue 30"),
                    ("blue-100", "Blue 100"),
                    ("blue-200", "Blue 200"),
                    ("blue-300", "Blue 300"),
                    ("blue-400", "Blue 400"),
                    ("blue-500", "Blue 500"),
                    ("blue-600", "Blue 600"),
                    ("blue-700", "Blue 700"),
                    ("blue-800", "Blue 800"),
                    ("yellow-100", "Yellow 100"),
                    ("yellow-200", "Yellow 200"),
                    ("yellow-300", "Yellow 300"),
                ],
                default="",
                max_length=50,
                verbose_name="Breadcrumbs background",
            ),
        ),
    ]
