# Generated by Django 4.2.4 on 2024-02-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_cms", "0059_fdspageextension_breadcrumbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="fdspageextension",
            name="breadcrumb_overlay",
            field=models.BooleanField(
                default=False,
                verbose_name="Lay the breadcrumbs over the page content. Works well with hero image headers.",
            ),
        ),
        migrations.AlterField(
            model_name="fdspageextension",
            name="search_index",
            field=models.BooleanField(
                default=True, verbose_name="Show in search results and search engines"
            ),
        ),
    ]
