# Generated by Django 4.2.4 on 2024-03-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import filer.fields.image


class Migration(migrations.Migration):
    replaces = [
        ("fds_cms", "0061_sharelinkscmsplugin_icons_only_and_more"),
        ("fds_cms", "0062_sharelinkscmsplugin_button_text_and_more"),
        ("fds_cms", "0063_remove_sharelinkscmsplugin_button_text_and_more"),
        ("fds_cms", "0064_alter_sharelinkscmsplugin_facebook_and_more"),
    ]

    dependencies = [
        ("fds_cms", "0060_fdspageextension_breadcrumb_overlay_and_more"),
        ("filer", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="icons_only",
            field=models.BooleanField(default=False, verbose_name="Only show icons"),
        ),
        migrations.AlterField(
            model_name="sharelinkscmsplugin",
            name="url",
            field=models.URLField(
                blank=True, help_text="Defaults to the current page's URL."
            ),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                default=None,
                help_text="Only available with the Native Share API. If sharing doesn't work, the image will be downloaded instead.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="clipboard",
            field=models.BooleanField(default=True, verbose_name="Copy to clipboard"),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="email",
            field=models.BooleanField(default=False, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="native_links",
            field=models.BooleanField(
                default=False,
                help_text="Only applies to the native share button.",
                verbose_name="Link instead of button",
            ),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="native_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Native share button label",
            ),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="twitter",
            field=models.BooleanField(default=True, verbose_name="Twitter"),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="facebook",
            field=models.BooleanField(default=False, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="mastodon",
            field=models.BooleanField(default=True, verbose_name="Mastodon"),
        ),
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="native_share",
            field=models.BooleanField(
                default=True,
                help_text="Great on mobile devices.",
                verbose_name="Native share",
            ),
        ),
    ]
