# Generated by Django 4.2.14 on 2024-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0065_pretixembedcmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="pretixembedcmsplugin",
            name="additional_settings",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="pretixembedcmsplugin",
            name="js_url",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="pretixembedcmsplugin",
            name="shop_url",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="sharelinkscmsplugin",
            name="native_links",
            field=models.BooleanField(
                default=False, verbose_name="Link instead of button"
            ),
        ),
    ]
