# Generated by Django 4.2.14 on 2024-07-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0066_pretixembedcmsplugin_additional_settings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pretixembedcmsplugin",
            name="additional_settings",
            field=models.CharField(blank=True, default=""),
        ),
    ]
