# Generated by Django 4.2.14 on 2024-08-12 08:49

from django.db import migrations, models

import fragdenstaat_de.fds_cms.models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0067_alter_pretixembedcmsplugin_additional_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="fdspageextension",
            name="frame_ancestors",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    fragdenstaat_de.fds_cms.models.validate_space_separated_urls
                ],
                verbose_name="Space separated list of allowed frame ancestor URLs.",
            ),
        ),
    ]
