# Generated by Django 4.2.16 on 2024-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0068_fdspageextension_frame_ancestors"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelinkscmsplugin",
            name="bluesky",
            field=models.BooleanField(default=True, verbose_name="BlueSky"),
        ),
        migrations.AlterField(
            model_name="sharelinkscmsplugin",
            name="twitter",
            field=models.BooleanField(default=False, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="vegachartcmsplugin",
            name="description",
            field=models.TextField(
                blank=True, help_text="Formatting with Markdown is supported."
            ),
        ),
    ]
