# Generated by Django 4.2.16 on 2024-11-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0069_sharelinkscmsplugin_bluesky_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharelinkscmsplugin",
            name="twitter",
        ),
    ]
