# Generated by Django 4.2.16 on 2025-02-17 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('datashow', '0002_column_facet_count'),
        ('fds_cms', '0070_remove_sharelinkscmsplugin_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatashowTableCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('query', models.TextField(blank=True)),
                ('limit', models.SmallIntegerField(default=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datashow.table')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DatashowDatasetTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='datashow.dataset')),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('banner', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
        ),
    ]
