# Generated by Django 4.2.16 on 2025-03-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('fds_cms', '0071_datashowtablecmsplugin_datashowdatasettheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datashowdatasettheme',
            name='banner',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='primarylinkcmsplugin',
            name='template',
            field=models.CharField(blank=True, choices=[('', 'Default template'), ('tile.html', 'Social tile template'), ('featured.html', 'Featured template'), ('campaign.html', 'Campaign template')], default='', max_length=50, verbose_name='Template'),
        ),
    ]
