# Generated by Django 4.2.16 on 2025-04-07 15:24

from django.db import migrations, models


def update_animation_field(apps, schema_editor):
    DropdownBannerCMSPlugin = apps.get_model("fds_cms", "DropdownBannerCMSPlugin")
    # used to be a boolean field, so values were casted to "false" and "true"
    DropdownBannerCMSPlugin.objects.filter(animation="false").update(animation="")
    DropdownBannerCMSPlugin.objects.filter(animation="true").update(animation="up")

class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0074_pagepreviewcmsplugin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropdownbannercmsplugin",
            name="animation",
            field=models.CharField(
                blank=True,
                choices=[("up", "Up"), ("down", "Down")],
                default="up",
                max_length=10,
                verbose_name="Animation when closing banner",
            ),
        ),
        migrations.RunPython(update_animation_field),
    ]
