# Generated by Django 4.2.16 on 2025-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0075_opensearchcmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="opensearchcmsplugin",
            name="urltemplate",
            field=models.URLField(default="$link"),
            preserve_default=False,
        ),
    ]
