# Generated by Django 4.2.16 on 2025-04-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0075_alter_dropdownbannercmsplugin_animation"),
        ("fds_cms", "0076_opensearchcmsplugin_urltemplate"),
    ]

    operations = []
