# Generated by Django 4.2.16 on 2025-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0077_merge_20250429_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="opensearchcmsplugin",
            name="filterconfig",
            field=models.JSONField(default=dict),
        ),
    ]
