# Generated by Django 4.2.16 on 2025-05-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('cookie_consent', '0004_cookie_natural_key'),
        ('fds_cms', '0078_opensearchcmsplugin_filterconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPixelCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('pixel_urls', models.TextField(help_text='URLs to the external pixels.')),
                ('cookie_group', models.ForeignKey(help_text='Cookie groups to which this pixel belongs.', on_delete=django.db.models.deletion.CASCADE, to='cookie_consent.cookiegroup')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
