# Generated by Django 5.2.1 on 2025-06-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_cms', '0079_externalpixelcmsplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foirequestlistcmsplugin',
            name='template',
            field=models.CharField(blank=True, choices=[('', 'Default template'), ('foirequest/cms_plugins/list_follow.html', 'Follow template'), ('foirequest/cms_plugins/map.html', 'Map template')], help_text='template used to display the plugin', max_length=250, verbose_name='template'),
        ),
    ]
