# Generated by Django 5.2.1 on 2025-07-14 14:55

from django.db import migrations, models

def migrate_section_border(apps, schema_editor):
    BorderedSectionCMSPlugin = apps.get_model("fds_cms", "BorderedSectionCMSPlugin")
    BorderedSectionCMSPlugin.objects.filter(border="blue").update(border="blue-20")
    BorderedSectionCMSPlugin.objects.filter(border="gray").update(border="gray-300")
    BorderedSectionCMSPlugin.objects.filter(border="yellow").update(border="yellow-200")

def reverse_migrate_section_border(apps, schema_editor):
    BorderedSectionCMSPlugin = apps.get_model("fds_cms", "BorderedSectionCMSPlugin")
    BorderedSectionCMSPlugin.objects.filter(border="blue-20").update(border="blue")
    BorderedSectionCMSPlugin.objects.filter(border="gray-300").update(border="gray")
    BorderedSectionCMSPlugin.objects.filter(border="yellow-200").update(border="yellow")

class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0080_alter_cardcmsplugin_background_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borderedsectioncmsplugin",
            name="border",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("primary", "Primary"),
                    ("primary-subtle", "Primary Subtle"),
                    ("secondary", "Secondary"),
                    ("secondary-subtle", "Secondary Subtle"),
                    ("info", "Info"),
                    ("info-subtle", "Info Subtle"),
                    ("success", "Success"),
                    ("success-subtle", "Success Subtle"),
                    ("warning", "Warning"),
                    ("warning-subtle", "Warning Subtle"),
                    ("danger", "Danger"),
                    ("danger-subtle", "Danger Subtle"),
                    ("white", "White"),
                    ("light", "Light"),
                    ("light-subtle", "Light Subtle"),
                    ("dark", "Dark"),
                    ("dark-subtle", "Dark Subtle"),
                    ("gray-100", "Gray 100"),
                    ("gray-200", "Gray 200"),
                    ("gray-300", "Gray 300"),
                    ("gray-400", "Gray 400"),
                    ("gray-500", "Gray 500"),
                    ("gray-600", "Gray 600"),
                    ("gray-700", "Gray 700"),
                    ("gray-800", "Gray 800"),
                    ("gray-900", "Gray 900"),
                    ("blue-10", "Blue 10"),
                    ("blue-20", "Blue 20"),
                    ("blue-30", "Blue 30"),
                    ("blue-100", "Blue 100"),
                    ("blue-200", "Blue 200"),
                    ("blue-300", "Blue 300"),
                    ("blue-400", "Blue 400"),
                    ("blue-500", "Blue 500"),
                    ("blue-600", "Blue 600"),
                    ("blue-700", "Blue 700"),
                    ("blue-800", "Blue 800"),
                    ("yellow-100", "Yellow 100"),
                    ("yellow-200", "Yellow 200"),
                    ("yellow-300", "Yellow 300"),
                ],
                default="gray",
                max_length=50,
                verbose_name="Border",
            ),
        ),
        migrations.RunPython(migrate_section_border, reverse_migrate_section_border),
    ]
