# Generated by Django 5.2.6 on 2025-09-22 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("fds_cms", "0081_alter_borderedsectioncmsplugin_border"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatawrapperCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "dw_url",
                    models.URLField(
                        help_text="Enter the “Visualization only” link from Datawrapper.",
                        validators=[
                            django.core.validators.URLValidator(
                                regex="https:\\/\\/datawrapper\\.dwcdn\\.net\\/.*"
                            )
                        ],
                        verbose_name="Datawrapper URL",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
