# Generated by Django 5.2.7 on 2025-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_cms', '0082_datawrappercmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageannotationcmsplugin',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pageannotationcmsplugin',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
