# Generated by Django 5.2.6 on 2025-11-24 14:33

import djangocms_frontend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0083_pageannotationcmsplugin_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designcontainercmsplugin",
            name="tag_type",
            field=djangocms_frontend.fields.TagTypeField(
                choices=[
                    ("div", "div"),
                    ("section", "section"),
                    ("article", "article"),
                    ("header", "header"),
                    ("footer", "footer"),
                    ("aside", "aside"),
                ],
                default="div",
                help_text="Select the HTML tag to be used.",
                max_length=255,
                verbose_name="Tag type",
            ),
        ),
    ]
