# Generated by Django 5.2.6 on 2025-11-24 14:51

import djangocms_attributes_field.fields
from django.db import migrations

def migrate_to_attributes(apps, schema_editor):
    DesignContainerCMSPlugin = apps.get_model("fds_cms", "DesignContainerCMSPlugin")
    containers = DesignContainerCMSPlugin.objects.exclude(extra_classes="")
    for container in containers:
        container.root_attributes["class"] = container.extra_classes
        container.save()

def migrate_from_attributes(apps, schema_editor):
    DesignContainerCMSPlugin = apps.get_model("fds_cms", "DesignContainerCMSPlugin")
    containers = DesignContainerCMSPlugin.objects.all()
    for container in containers:
        container.extra_classes = container.root_attributes.get("class", "")
        container.save()

class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0084_designcontainer_add_tagtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="designcontainercmsplugin",
            name="container_attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AddField(
            model_name="designcontainercmsplugin",
            name="root_attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.RunPython(migrate_to_attributes, migrate_from_attributes),
        migrations.AlterField(
            model_name="borderedsectioncmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardcmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardheadercmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardiconcmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardimagecmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardinnercmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardlinkcmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="modalcmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="modalcmsplugin",
            name="dialog_attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AlterField(
            model_name="revealmorecmsplugin",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.RemoveField(
            model_name="designcontainercmsplugin",
            name="extra_classes",
        ),
    ]
