# Generated by Django 5.2.10 on 2026-04-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('fds_cms', '0085_designcontainer_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAlertCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('button_label', models.CharField(blank=True, max_length=255)),
                ('query', models.CharField(blank=True, max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
