# Generated by Django 2.2.4 on 2019-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationgift",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="donationgiftformcmsplugin",
            name="next_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
