# Generated by Django 2.2.4 on 2019-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0008_auto_20191119_1355"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="identifier",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="donation",
            name="method",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="donation",
            name="received_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="identifier",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
