# Generated by Django 2.2.4 on 2019-12-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0011_auto_20191205_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="amount_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
