# Generated by Django 2.2.4 on 2019-12-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0012_donation_amount_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="first_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="donation",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
