# Generated by Django 2.2.4 on 2020-01-28 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0014_donor_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="duplicate",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="fds_donation.Donor",
            ),
        ),
    ]
