# Generated by Django 2.2.4 on 2020-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0015_auto_20200128_1346"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="receipt_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
