# Generated by Django 3.0.5 on 2020-05-28 10:02

from django.db import migrations


def move_to_many_subscriptions(apps, schema_editor):
    Donor = apps.get_model("fds_donation", "Donor")
    for donor in Donor.objects.filter(subscription__isnull=False):
        donor.subscriptions.add(donor.subscription)


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0021_auto_20200528_1201"),
    ]

    operations = [
        migrations.RunPython(move_to_many_subscriptions),
    ]
