# Generated by Django 3.0.5 on 2020-05-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0022_auto_20200528_1202"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="subscription",
        ),
    ]
