# Generated by Django 3.0.7 on 2020-07-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0025_auto_20200701_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
