# Generated by Django 3.0.7 on 2020-07-01 15:04

from django.db import migrations, models


def add_donation_number(apps, schema_editor):
    from django.db.models.functions import RowNumber

    Donation = apps.get_model("fds_donation", "Donation")

    donations = Donation.objects.filter(completed=True).annotate(
        new_number=models.Window(
            expression=RowNumber(),
            partition_by=[models.F("donor_id")],
            order_by=models.F("timestamp").asc(),
        )
    )
    for d in donations:
        if d.number != d.new_number:
            Donation.objects.filter(id=d.id).update(number=d.new_number)


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0026_donation_number"),
    ]

    operations = [migrations.RunPython(add_donation_number)]
