# Generated by Django 3.0.8 on 2020-08-26 13:15
import fragdenstaat_de.fds_donation.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_donation", "0027_auto_20200701_1704"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultDonation",
            fields=[],
            options={
                "verbose_name": "FragDenStaat Spenden",
                "verbose_name_plural": "FragDenStaat Spenden",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fds_donation.donation",),
        ),
        migrations.AddField(
            model_name="donation",
            name="project",
            field=models.CharField(
                choices=fragdenstaat_de.fds_donation.models.get_project_choices,
                default=fragdenstaat_de.fds_donation.models.DEFAULT_DONATION_PROJECT,
                max_length=40,
            ),
        ),
    ]
