# Generated by Django 3.0.8 on 2020-12-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0029_donationprogressbarcmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationprogressbarcmsplugin",
            name="reached_goal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
