# Generated by Django 3.2.8 on 2021-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0034_alter_donor_salutation"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationprogressbarcmsplugin",
            name="received_donations_only",
            field=models.BooleanField(default=False),
        ),
    ]
