# Generated by Django 3.2.8 on 2021-11-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0036_donationformcmsplugin_extra_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationprogressbarcmsplugin",
            name="white_text",
            field=models.BooleanField(default=False),
        ),
    ]
