# Generated by Django 4.0.7 on 2022-09-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("fds_donation", "0037_donationprogressbarcmsplugin_white_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={
                "get_latest_by": "timestamp",
                "ordering": ("-timestamp",),
                "verbose_name": "donation",
                "verbose_name_plural": "donations",
            },
        ),
        migrations.AlterModelOptions(
            name="donor",
            options={
                "get_latest_by": "first_donation",
                "ordering": ("-id",),
                "verbose_name": "donor",
                "verbose_name_plural": "donors",
            },
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="min_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donationformcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="donationgiftformcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="donationprogressbarcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
