# Generated by Django 4.0.7 on 2022-09-20 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0039_donationformcmsplugin_gift_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationGiftOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("first_name", models.CharField(blank=True, max_length=256)),
                ("last_name", models.CharField(blank=True, max_length=256)),
                ("company_name", models.CharField(blank=True, max_length=256)),
                ("address", models.CharField(blank=True, max_length=256)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=256)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("note", models.TextField(blank=True)),
                ("shipped", models.DateTimeField(blank=True, null=True)),
                ("tracking", models.CharField(blank=True, max_length=255)),
                (
                    "donation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fds_donation.donation",
                    ),
                ),
                (
                    "donation_gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_donation.donationgift",
                    ),
                ),
            ],
            options={
                "verbose_name": "donation gift order",
                "verbose_name_plural": "donation gift orders",
                "ordering": ("timestamp",),
            },
        ),
    ]
