# Generated by Django 4.1.4 on 2023-01-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0042_donationformcmsplugin_default_gift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="received",
        ),
    ]
