# Generated by Django 4.2.14 on 2024-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0043_remove_donation_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="open_in_new_tab",
            field=models.BooleanField(default=False),
        ),
    ]
