# Generated by Django 4.2.16 on 2024-11-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0045_donationprogressbarcmsplugin_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationformcmsplugin',
            name='next_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
