# Generated by Django 4.2.16 on 2024-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0046_donationformcmsplugin_next_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="extra_action_label",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="extra_action_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
