# Generated by Django 4.2.16 on 2025-01-08 13:00

from django.db import migrations, models
import fragdenstaat_de.fds_donation.models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0047_donation_extra_action_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationformcmsplugin',
            name='next_url',
            field=models.CharField(blank=True, max_length=255, validators=[fragdenstaat_de.fds_donation.models.validate_allowed_host_and_scheme]),
        ),
    ]
