# Generated by Django 4.2.16 on 2025-03-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0048_alter_donationformcmsplugin_next_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredDonation',
            fields=[
            ],
            options={
                'verbose_name': 'Deferred Donation',
                'verbose_name_plural': 'Deferred Donation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fds_donation.donation',),
        ),
    ]
