# Generated by Django 4.2.16 on 2025-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0049_deferreddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationgift',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
