# Generated by Django 4.2.16 on 2025-03-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0050_donationgift_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationgiftorder',
            options={'ordering': ('-timestamp',), 'verbose_name': 'donation gift order', 'verbose_name_plural': 'donation gift orders'},
        ),
    ]
