# Generated by Django 4.2.16 on 2025-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0051_alter_donationgiftorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='form_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
