# Generated by Django 4.2.16 on 2025-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0052_donation_form_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
