# Generated by Django 4.2.16 on 2025-04-24 07:34

from django.db import migrations, models
import django.db.models.deletion
import djangocms_frontend.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('fds_donation', '0053_donation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDonationButtonCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('interval', models.CharField(choices=[('once', 'Only once'), ('recurring', 'Only recurring'), ('once_recurring', 'Both')], max_length=20)),
                ('amount_presets', models.CharField(blank=True, max_length=255)),
                ('initial_amount', models.IntegerField(blank=True, null=True)),
                ('initial_interval', models.IntegerField(blank=True, null=True)),
                ('min_amount', models.IntegerField(default=0)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('action_label', models.CharField(blank=True, max_length=255)),
                ('attributes', djangocms_frontend.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
