# Generated by Django 4.2.16 on 2025-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0054_emaildonationbuttoncmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationformcmsplugin',
            name='interval_choices',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
