# Generated by Django 4.2.16 on 2025-04-29 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0055_donationformcmsplugin_interval_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationFormViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Donation Form View Count',
                'verbose_name_plural': 'Donation Form View Counts',
                'ordering': ('-last_updated',),
                'indexes': [models.Index(fields=['path', 'reference'], name='fds_donatio_path_4b76f9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='donationformviewcount',
            constraint=models.UniqueConstraint(fields=('path', 'reference'), name='unique_path_ref'),
        ),
    ]
