# Generated by Django 4.2.16 on 2025-04-30 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0056_donationformviewcount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donationformviewcount',
            name='unique_path_ref',
        ),
        migrations.RemoveIndex(
            model_name='donationformviewcount',
            name='fds_donatio_path_4b76f9_idx',
        ),
        migrations.AddField(
            model_name='donationformviewcount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='donationformviewcount',
            index=models.Index(fields=['path', 'reference', 'date'], name='fds_donatio_path_38930d_idx'),
        ),
        migrations.AddConstraint(
            model_name='donationformviewcount',
            constraint=models.UniqueConstraint(fields=('path', 'reference', 'date'), name='unique_path_ref'),
        ),
    ]
