# Generated by Django 5.2.1 on 2025-06-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0057_remove_donationformviewcount_unique_path_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationformcmsplugin',
            name='payment_methods',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='donationformcmsplugin',
            name='hide_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationformcmsplugin',
            name='hide_account',
            field=models.BooleanField(default=False),
        ),
    ]
