# Generated by Django 5.2.1 on 2025-06-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0058_donationformcmsplugin_payment_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='become_user',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_allowed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='receipt',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
