# Generated by Django 5.2.1 on 2025-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0059_alter_donor_become_user_alter_donor_contact_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='form_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='donation',
            name='keyword',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='donation',
            name='reference',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
