# Generated by Django 5.2.1 on 2025-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0060_alter_donation_form_url_alter_donation_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationformcmsplugin',
            name='quick_payment',
            field=models.CharField(blank=True, choices=[('', 'No quick payment'), ('show', 'Show quick payment options'), ('only', 'Only quick payment options')], max_length=20),
        ),
    ]
