# Generated by Django 5.1.1 on 2025-07-03 11:17

import django.db.models.deletion
from django.db import migrations, models

import fragdenstaat_de.fds_donation.models

class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0061_donationformcmsplugin_quick_payment'),
        ('froide_payment', '0020_subscription_cancel_trigger_subscription_canceled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateTimeField()),
                ('interval', models.IntegerField(choices=fragdenstaat_de.fds_donation.models.get_recurring_interval_choices)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('', 'No reason given'), ('financial', 'Financial reasons'), ('unintended', 'Mistakenly set up, do not remember doing so'), ('lost', 'I do not want to support this project anymore'), ('other', 'Other')], default='', help_text='Reason for cancellation', max_length=255)),
                ('cancel_feedback', models.TextField(blank=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='fds_donation.donor')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='froide_payment.subscription')),
            ],
            options={
                'verbose_name': 'recurring pattern',
                'verbose_name_plural': 'recurring pattern',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='fds_donation.recurrence'),
        ),
    ]
