# Generated by Django 5.1.1 on 2025-07-07 08:38
import fragdenstaat_de.fds_donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0062_recurrence_donation_recurrence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrence',
            options={'verbose_name': 'Recurring donation', 'verbose_name_plural': 'Recurring donations'},
        ),
        migrations.AddField(
            model_name='recurrence',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recurrence",
            name="project",
            field=models.CharField(
                choices=fragdenstaat_de.fds_donation.models.get_project_choices,
                default=fragdenstaat_de.fds_donation.models.DEFAULT_DONATION_PROJECT,
                max_length=40,
            ),
        ),
    ]
