# Generated by Django 5.2.7 on 2025-11-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("fds_donation", "0063_alter_recurrence_options_recurrence_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteDonationFormCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("remote_url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("once", "Only once"),
                            ("recurring", "Only recurring"),
                            ("once_recurring", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interval_choices", models.CharField(blank=True, max_length=255)),
                ("amount_presets", models.CharField(blank=True, max_length=255)),
                ("initial_amount", models.IntegerField(blank=True, null=True)),
                ("initial_interval", models.IntegerField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("keyword", models.CharField(blank=True, max_length=255)),
                ("open_in_new_tab", models.BooleanField(default=True)),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
