# Generated by Django 5.2.7 on 2025-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0064_remotedonationformcmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotedonationformcmsplugin",
            name="show_title",
            field=models.BooleanField(default=True),
        ),
    ]
