# Generated by Django 5.2.7 on 2025-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0065_remotedonationformcmsplugin_show_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildonationbuttoncmsplugin",
            name="prefilled_amount",
            field=models.BooleanField(default=True),
        ),
    ]
