# Generated by Django 5.2.7 on 2025-12-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0066_emaildonationbuttoncmsplugin_prefilled_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationgift",
            name="download_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="donationgift",
            name="gift_type",
            field=models.IntegerField(
                choices=[(1, "Physical"), (2, "Virtual")], default=1
            ),
        ),
    ]
