# Generated by Django 5.2.7 on 2025-12-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0067_donationgift_download_url_donationgift_gift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
