# Generated by Django 5.2.7 on 2025-12-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0068_donor_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationgift',
            name='min_recurring_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='donationgift',
            name='min_streak_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationgift',
            name='download_url',
            field=models.TextField(blank=True),
        ),
    ]
