# Generated by Django 5.2.10 on 2026-02-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0069_donationgift_min_recurring_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='recurrence_streak_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
