# Generated by Django 5.2.10 on 2026-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0070_donor_recurrence_streak_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='new_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
