# Generated by Django 5.2.10 on 2026-04-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('fds_donation', '0070_donor_recurrence_streak_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRecurrenceFormCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('next_url', models.CharField(blank=True, max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
