# Generated by Django 5.2.10 on 2026-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0071_upgraderecurrenceformcmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderecurrenceformcmsplugin',
            name='choice_count',
            field=models.SmallIntegerField(default=3),
        ),
    ]
