# Generated by Django 5.2.10 on 2026-03-11 13:07

from django.db import migrations


def move_donor_attributes(apps, schema_editor):
    import json

    Donor = apps.get_model("fds_donation", "Donor")
    donors = Donor.objects.filter(attributes__isnull=False).only("id", "attributes")
    for donor in donors:
        attr = donor.attributes
        attr_keys = list(attr.keys())
        if not attr_keys:
            continue
        new_attr = {}
        for key in attr_keys:
            val = attr[key]
            try:
                # Try to convert bad stringified Python data in attributes
                obj = json.loads(val.replace("'", '"'))
                new_attr[key] = obj
            except json.decoder.JSONDecodeError:
                new_attr[key] = val
        Donor.objects.filter(id=donor.id).update(new_attributes=new_attr)


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0071_donor_new_attributes'),
    ]

    operations = [
        migrations.RunPython(move_donor_attributes)
    ]
