# Generated by Django 5.2.10 on 2026-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0072_auto_20260311_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='attributes',
        ),
        migrations.RenameField(
            model_name="donor",
            old_name="new_attributes",
            new_name="attributes",
        ),
    ]
