# Generated by Django 5.2.10 on 2026-04-28 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0072_upgraderecurrenceformcmsplugin_choice_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('prompt_upgrade_recurrence', 'prompt recurrence upgrade'), ('upgrade_recurrence', 'upgraded recurrence')], max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(default=dict)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fds_donation.donor')),
            ],
            options={
                'verbose_name': 'donor event',
                'verbose_name_plural': 'donor events',
            },
        ),
    ]
