# Generated by Django 5.2.10 on 2026-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0073_donorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='last_upgrade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgraderecurrenceformcmsplugin',
            name='days_since',
            field=models.IntegerField(default=0),
        ),
    ]
