# Generated by Django 5.2.10 on 2026-05-27 07:56

import django.db.models.deletion
import fragdenstaat_de.fds_donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0074_recurrence_last_upgrade_and_more'),
        ('flowcontrol', '0005_emailalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorevent',
            name='kind',
            field=models.CharField(choices=fragdenstaat_de.fds_donation.models.get_donor_event_kinds, max_length=255),
        ),
        migrations.CreateModel(
            name='DonorTagActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('remove', models.BooleanField(default=False, help_text='If checked will remove the tag from the donor instead of adding it.', verbose_name='Remove tag')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fds_donation.donortag', verbose_name='Donor Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
    ]
