# Generated by Django 5.2.10 on 2026-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0075_alter_donorevent_kind_donortagactionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationgiftorder',
            name='processing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
