# Generated by Django 5.2.15 on 2026-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0076_donationgiftorder_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderecurrenceformcmsplugin',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
