# Generated by Django 5.2.15 on 2026-07-15 11:58

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0077_upgraderecurrenceformcmsplugin_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationprogressbarcmsplugin',
            name='initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=decimal.Decimal, max_digits=10),
        ),
    ]
