# Generated by Django 5.2.15 on 2026-07-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_donation', '0078_donationprogressbarcmsplugin_initial_amount'),
        ('flowcontrol', '0007_alter_flowrun_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyDonatedActionConfig',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('since_date', models.DateTimeField(blank=True, null=True)),
                ('since_days', models.PositiveSmallIntegerField(default=0)),
                ('negate', models.BooleanField(default=False, help_text="If hasn't recently donated", verbose_name='Negate condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
    ]
