# Generated by Django 5.2.15 on 2026-09-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('fds_donation', '0079_recentlydonatedactionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDonorTagCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('negate', models.BooleanField(default=False, help_text="If doesn't have tag", verbose_name='Negate condition')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fds_donation.donortag', verbose_name='Donor Tag')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
